{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Auth Attemps/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status) (rate(auth_attempts_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Revenue (₿/m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizzas Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(pizza_sold_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Pizzas Sold"
    },
    {
     "expr": "rate(pizza_creation_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Creation Failures"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(service_latency_ms_total{source=\"jwt-pizza-service\", endpoint=\"/api/auth\", method=\"PUT\"}[1m])",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(service_latency_ms_total{source=\"jwt-pizza-service\", endpoint=\"/api/order\"}[1m])",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percentage_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percentage_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}